import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncServerDB1785524345653 implements MigrationInterface {
    name = 'SyncServerDB1785524345653'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_3ce7e1ecb0bee6873c2a6566ed6"`);
        await queryRunner.query(`ALTER TABLE "opportunity_trackings" RENAME COLUMN "stage" TO "stage_id"`);
        await queryRunner.query(`ALTER TYPE "public"."opportunity_trackings_stage_enum" RENAME TO "opportunity_trackings_stage_id_enum"`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(255) NOT NULL, "correo" character varying(255), "telefono" character varying(50), "website" character varying(255), "direccion" character varying(512), "estatus" boolean NOT NULL DEFAULT true, "ejecutivo_id" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tblstagescatalog" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(120) NOT NULL, "blnstatus" boolean NOT NULL DEFAULT true, "bln_show_dashboard" boolean NOT NULL DEFAULT true, "pipeline_id" uuid NOT NULL, "display_order" integer NOT NULL DEFAULT '0', "strcolor" character varying(20), "blninitial" boolean NOT NULL DEFAULT false, "intmaxdays" integer, "dtmcreated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dtmlastmodified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_288f5036149fd7e3931567296ed" UNIQUE ("pipeline_id", "strname"), CONSTRAINT "PK_ebc58cb57871aea9219c96c6690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tblpipelinescatalog" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(120) NOT NULL, "strdescription" character varying(500), "blnstatus" boolean NOT NULL DEFAULT true, "dtmcreated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dtmlastmodified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "intlastmodifiedby" integer NOT NULL DEFAULT '1', CONSTRAINT "UQ_21c5c54ef8b817b68623d3ea7bd" UNIQUE ("strname"), CONSTRAINT "PK_eddde900eb35ee0acaf8f9bbd9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opportunity_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileName" character varying(255) NOT NULL, "filePath" character varying(512) NOT NULL, "title" character varying(255), "date" date, "opportunityId" uuid NOT NULL, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_73cd155bbededebad3c2cbd7735" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileName" character varying(255) NOT NULL, "filePath" character varying(512) NOT NULL, "title" character varying(255), "productId" uuid NOT NULL, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d741e1a2d0cde49c1f897048626" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "descripcion" text, "precioBase" numeric(10,2), "unidadMedida" text NOT NULL DEFAULT 'Pieza', "observaciones" text, "status" boolean NOT NULL DEFAULT true, "imagenPortada" character varying(512), "createdById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opportunity_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "opportunityId" uuid NOT NULL, "productId" uuid NOT NULL, "cantidad" numeric(10,2) NOT NULL DEFAULT '1', CONSTRAINT "PK_b6dc230738166b79452dd8dcd54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tblbusinesslines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(255) NOT NULL, "blnstatus" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_2f16a4a59d225c52481ca8444af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tbldeliverytypes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(255) NOT NULL, "blnstatus" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a28ad8fd752fb929c2f97791d3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tblicensings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(255) NOT NULL, "blnstatus" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f2d1bd208873a8f6b5757281e47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_stages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(120) NOT NULL, "blnstatus" boolean NOT NULL DEFAULT true, "bln_show_dashboard" boolean NOT NULL DEFAULT true, "helpdesk_id" uuid NOT NULL, "display_order" integer NOT NULL DEFAULT '0', "strcolor" character varying(20), "blninitial" boolean NOT NULL DEFAULT false, "intmaxdays" integer, "dtmcreated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dtmlastmodified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a1faa0d64e8d53484b72248c529" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "helpdesks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(255) NOT NULL, "strdescription" text, "blnstatus" boolean NOT NULL DEFAULT true, "dtmcreated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dtmlastmodified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_77f02240860ca47509d1a57aa98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_number" SERIAL NOT NULL, "strtitle" character varying(255) NOT NULL, "tipo_incidencia" character varying(255) NOT NULL, "description" text NOT NULL, "fecha_apertura" TIMESTAMP NOT NULL DEFAULT now(), "fecha_cierre" TIMESTAMP, "notas_resolucion" text, "priority" integer NOT NULL DEFAULT '1', "alert_sent" boolean NOT NULL DEFAULT false, "archived" boolean NOT NULL DEFAULT false, "cliente_id" uuid, "responsable_id" uuid, "helpdesk_id" uuid NOT NULL, "stage_id" uuid NOT NULL, "stage_entered_at" TIMESTAMP NOT NULL DEFAULT now(), "contactName" character varying(255), "contactEmail" character varying(255), "contactPhone" character varying(255), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plans" ("plan_id" SERIAL NOT NULL, "plan_name" character varying(100) NOT NULL, "price" numeric(10,2) NOT NULL DEFAULT '0', "tokens_limit" bigint NOT NULL DEFAULT '0', "billing_period_months" integer NOT NULL DEFAULT '1', "blnstatus" boolean NOT NULL DEFAULT true, "dtmcreated" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "dtmlastmodified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_084714de33798c5b96f12725f7e" PRIMARY KEY ("plan_id"))`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "schema_name" character varying(63) NOT NULL, "plan_id" integer, "next_renewal_date" TIMESTAMP WITH TIME ZONE, "is_active" boolean NOT NULL DEFAULT true, "allow_extra" boolean NOT NULL DEFAULT false, "logo" character varying(512), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c2a961556326eec0e3b19f3ced5" UNIQUE ("schema_name"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_renewal_queue" ("id" SERIAL NOT NULL, "tenant_id" character varying(63) NOT NULL, "plan_id" integer NOT NULL, "billing_period_months" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0b5219ff2950ff66c9d8f23db09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "helpdesk_cron_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "helpdesk_id" uuid NOT NULL, "cron_mode" character varying(20) NOT NULL DEFAULT 'fixed', "cron_time" character varying(5) DEFAULT '08:00', "cron_interval_hours" integer, "cron_interval_minutes" integer, "blnstatus" boolean NOT NULL DEFAULT true, "dtmcreated" TIMESTAMP NOT NULL DEFAULT now(), "dtmlastmodified" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_44903aa0b7b587597e1142d28a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_interactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "comment" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "ticket_id" uuid NOT NULL, CONSTRAINT "PK_9a6d8ebb8568b1e08c202352353" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transaction_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "prompt_tokens" integer NOT NULL DEFAULT '0', "completion_tokens" integer NOT NULL DEFAULT '0', "total_tokens" integer NOT NULL DEFAULT '0', "fecha_procesamiento" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_extra" boolean NOT NULL DEFAULT false, "action_name" character varying(255), CONSTRAINT "PK_1e2444ea77f6b5952b4ab7cb9a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dashboard_indicators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "type" character varying(50) NOT NULL DEFAULT 'count', "pipeline_id" uuid, "helpdesk_id" uuid, "stage_ids" text, "color" character varying(50), "display_order" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3cf12ddb3c11e81efd0e2451d2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tbltypeactivities" ("id" SERIAL NOT NULL, "strname" character varying NOT NULL, "blnstatus" boolean NOT NULL, CONSTRAINT "PK_ece08c0992a238ec5d9d7b63b1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tbloportunitylabels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strname" character varying(255), "field_key" character varying(50), "blnstatus" boolean NOT NULL DEFAULT true, "dtmlastmodified" TIMESTAMP, "uuidlastmodifiedby" uuid, CONSTRAINT "UQ_9f16d008e337f8d51a29c787808" UNIQUE ("field_key"), CONSTRAINT "PK_d5651a1a004daaeaac4af6da08a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" character varying(50) NOT NULL, "related_id" character varying(255), "read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "channel_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channel" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "appId" character varying(255), "accountId" character varying(255), "phoneNumberId" character varying(255), "accessToken" character varying(2048), "verifyToken" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_71b592f5e0da6907fce0f0654cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channel" character varying(50) NOT NULL, "externalId" character varying(255) NOT NULL, "clientName" character varying(255) NOT NULL, "clientId" uuid, "assignedUserId" uuid, "botActive" boolean NOT NULL DEFAULT true, "channelConfigId" uuid, "summary" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_sub_agents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "context" text, "tools" jsonb, "temperature" double precision NOT NULL DEFAULT '0.7', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b74af48672e40ccdf0e7d661cd1" UNIQUE ("key"), CONSTRAINT "PK_3ac3f8c129d95a1140fae781b17" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversationId" uuid NOT NULL, "sender" character varying(50) NOT NULL, "senderUserId" uuid, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_agent_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isActive" boolean NOT NULL DEFAULT true, "context" text, "defaultReplies" text, "temperature" double precision NOT NULL DEFAULT '0.7', "modelProvider" character varying(50) NOT NULL DEFAULT 'gemini', "modelName" character varying(100) NOT NULL DEFAULT 'gemini-1.5-flash', "openaiApiKey" character varying(255), "openaiEndpoint" character varying(512), "openaiApiVersion" character varying(50), "openaiEmbeddingModel" character varying(100) NOT NULL DEFAULT 'text-embedding-ada-002', "geminiApiKey" character varying(255), "watsonxApiKey" character varying(255), "watsonxProjectId" character varying(255), "watsonxRegion" character varying(100), "watsonxEmbeddingModel" character varying(100) NOT NULL DEFAULT 'ibm/slate-125m-english-rtrvr', "reminderOffsetMinutes" integer NOT NULL DEFAULT '60', "maxNewTokens" integer NOT NULL DEFAULT '2048', "historyMessageLimit" integer NOT NULL DEFAULT '10', "defaultUserId" uuid, CONSTRAINT "PK_4db9af4608dfaa1179e26dd62bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opportunity_contacts" ("opportunitiesId" uuid NOT NULL, "clientsId" uuid NOT NULL, CONSTRAINT "PK_9d0eee6236cf01e6085a7c21a6c" PRIMARY KEY ("opportunitiesId", "clientsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7d00109580422761c6da2aa35" ON "opportunity_contacts" ("opportunitiesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_73fb9c255cb264c56fc9783295" ON "opportunity_contacts" ("clientsId") `);
        await queryRunner.query(`CREATE TABLE "activity_contacts" ("activitiesId" uuid NOT NULL, "clientsId" uuid NOT NULL, CONSTRAINT "PK_385cfbcf6795d4f3c9dfce7b680" PRIMARY KEY ("activitiesId", "clientsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc2f54f67216c56a0e28d7040f" ON "activity_contacts" ("activitiesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0461d2145d72ac02cb1f4496a" ON "activity_contacts" ("clientsId") `);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "etapa"`);
        await queryRunner.query(`DROP TYPE "public"."opportunities_etapa_enum"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "linea_negocio"`);
        await queryRunner.query(`DROP TYPE "public"."opportunities_linea_negocio_enum"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "tipo_entrega"`);
        await queryRunner.query(`DROP TYPE "public"."opportunities_tipo_entrega_enum"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "licenciamiento"`);
        await queryRunner.query(`DROP TYPE "public"."opportunities_licenciamiento_enum"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "activityType"`);
        await queryRunner.query(`DROP TYPE "public"."activities_activitytype_enum"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "opportunity_id"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "pipeline_id" uuid`);
        await queryRunner.query(`INSERT INTO "tblpipelinescatalog" ("id", "strname") VALUES ('00000000-0000-0000-0000-000000000001', 'Pipeline Migración') ON CONFLICT DO NOTHING`);
        await queryRunner.query(`UPDATE "opportunities" SET "pipeline_id" = '00000000-0000-0000-0000-000000000001' WHERE "pipeline_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "pipeline_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "stage_id" uuid`);
        await queryRunner.query(`INSERT INTO "tblstagescatalog" ("id", "strname", "pipeline_id") VALUES ('00000000-0000-0000-0000-000000000002', 'Etapa Migración', '00000000-0000-0000-0000-000000000001') ON CONFLICT DO NOTHING`);
        await queryRunner.query(`UPDATE "opportunities" SET "stage_id" = '00000000-0000-0000-0000-000000000002' WHERE "stage_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "stage_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "linea_negocio_id" uuid`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "tipo_entrega_id" uuid`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "licenciamiento_id" uuid`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "stage_entered_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "priority" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "typeActivityId" integer`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "companyId" uuid`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "notified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "activity_id" uuid`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "correo" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "empresa" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_b12ed2b583eebb41169a8fb64de"`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "cliente_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "empresa" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opportunity_trackings" DROP COLUMN "stage_id"`);
        await queryRunner.query(`ALTER TABLE "opportunity_trackings" ADD "stage_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('superadmin', 'admin', 'executive')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'executive'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "activity" TYPE text USING "activity"::text`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "FK_d006d797a7fb8586365e3a741ec" FOREIGN KEY ("ejecutivo_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_5016a1ccedbea5f26d46376d6b2" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tblstagescatalog" ADD CONSTRAINT "FK_5722459e77f4db2a760c7b888db" FOREIGN KEY ("pipeline_id") REFERENCES "tblpipelinescatalog"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunity_files" ADD CONSTRAINT "FK_4dab24c743f43a61cdcb9c52658" FOREIGN KEY ("opportunityId") REFERENCES "opportunities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_files" ADD CONSTRAINT "FK_56627602b737452ac8e95a0ac78" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_de1043dff8f68e83a20480b00f7" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunity_products" ADD CONSTRAINT "FK_d64e2b99803fd0de5f48b40202d" FOREIGN KEY ("opportunityId") REFERENCES "opportunities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunity_products" ADD CONSTRAINT "FK_71f53a0a0d3d828a4b24e81a64e" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_b12ed2b583eebb41169a8fb64de" FOREIGN KEY ("cliente_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_be657f80d27287715b533b080fa" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_51392868612157f01fc61a6ee2d" FOREIGN KEY ("pipeline_id") REFERENCES "tblpipelinescatalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_6b809748751441914b5a7068cc5" FOREIGN KEY ("stage_id") REFERENCES "tblstagescatalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_dd8f6e7c9c029545b56717efe07" FOREIGN KEY ("linea_negocio_id") REFERENCES "tblbusinesslines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_0caa550ba1e8af228a444f41c50" FOREIGN KEY ("tipo_entrega_id") REFERENCES "tbldeliverytypes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_6cb1c429c65cfa6c137262f524d" FOREIGN KEY ("licenciamiento_id") REFERENCES "tblicensings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunity_trackings" ADD CONSTRAINT "FK_f7377ab7b0daab81737dab9d74b" FOREIGN KEY ("stage_id") REFERENCES "tblstagescatalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_stages" ADD CONSTRAINT "FK_015df5b240821ddab339ec120c5" FOREIGN KEY ("helpdesk_id") REFERENCES "helpdesks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_db78a3be4e72f208821ecb0594a" FOREIGN KEY ("cliente_id") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_d29d3d90cac066e223c7ca8a2f8" FOREIGN KEY ("responsable_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bdfbcf4d15d865c4b5a47457f62" FOREIGN KEY ("helpdesk_id") REFERENCES "helpdesks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_7efefd7123dc764ffaee4b4b0a2" FOREIGN KEY ("stage_id") REFERENCES "ticket_stages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_919d143d2411832db812bbc600e" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_renewal_queue" ADD CONSTRAINT "FK_5b319b263e6a648b59823492780" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "helpdesk_cron_config" ADD CONSTRAINT "FK_82a7a900233deec55b3728bf687" FOREIGN KEY ("helpdesk_id") REFERENCES "helpdesks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_interactions" ADD CONSTRAINT "FK_015664a3fc2943f22209b488ad4" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_ee6a5903f9e17b283488a3a4017" FOREIGN KEY ("typeActivityId") REFERENCES "tbltypeactivities"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_f6deb4e21ba78416f476cd661e1" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_353491f8baaf582389847f43682" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_2882c536d4eecfd496132b20eeb" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_ac00a0b3bbe982fa019f0e4e60f" FOREIGN KEY ("assignedUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_2e3ef16d5e4debdb283906c3df7" FOREIGN KEY ("channelConfigId") REFERENCES "channel_configs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2868049bbe999cdf09aed764400" FOREIGN KEY ("senderUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_agent_configs" ADD CONSTRAINT "FK_105b5beccf07f2b988de1e9ad79" FOREIGN KEY ("defaultUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opportunity_contacts" ADD CONSTRAINT "FK_a7d00109580422761c6da2aa354" FOREIGN KEY ("opportunitiesId") REFERENCES "opportunities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "opportunity_contacts" ADD CONSTRAINT "FK_73fb9c255cb264c56fc97832958" FOREIGN KEY ("clientsId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "activity_contacts" ADD CONSTRAINT "FK_cc2f54f67216c56a0e28d7040f5" FOREIGN KEY ("activitiesId") REFERENCES "activities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "activity_contacts" ADD CONSTRAINT "FK_f0461d2145d72ac02cb1f4496a0" FOREIGN KEY ("clientsId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "activity_contacts" DROP CONSTRAINT "FK_f0461d2145d72ac02cb1f4496a0"`);
        await queryRunner.query(`ALTER TABLE "activity_contacts" DROP CONSTRAINT "FK_cc2f54f67216c56a0e28d7040f5"`);
        await queryRunner.query(`ALTER TABLE "opportunity_contacts" DROP CONSTRAINT "FK_73fb9c255cb264c56fc97832958"`);
        await queryRunner.query(`ALTER TABLE "opportunity_contacts" DROP CONSTRAINT "FK_a7d00109580422761c6da2aa354"`);
        await queryRunner.query(`ALTER TABLE "ai_agent_configs" DROP CONSTRAINT "FK_105b5beccf07f2b988de1e9ad79"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2868049bbe999cdf09aed764400"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_2e3ef16d5e4debdb283906c3df7"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_ac00a0b3bbe982fa019f0e4e60f"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_2882c536d4eecfd496132b20eeb"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_353491f8baaf582389847f43682"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_f6deb4e21ba78416f476cd661e1"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_ee6a5903f9e17b283488a3a4017"`);
        await queryRunner.query(`ALTER TABLE "ticket_interactions" DROP CONSTRAINT "FK_015664a3fc2943f22209b488ad4"`);
        await queryRunner.query(`ALTER TABLE "helpdesk_cron_config" DROP CONSTRAINT "FK_82a7a900233deec55b3728bf687"`);
        await queryRunner.query(`ALTER TABLE "tenant_renewal_queue" DROP CONSTRAINT "FK_5b319b263e6a648b59823492780"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_919d143d2411832db812bbc600e"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_7efefd7123dc764ffaee4b4b0a2"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bdfbcf4d15d865c4b5a47457f62"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_d29d3d90cac066e223c7ca8a2f8"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_db78a3be4e72f208821ecb0594a"`);
        await queryRunner.query(`ALTER TABLE "ticket_stages" DROP CONSTRAINT "FK_015df5b240821ddab339ec120c5"`);
        await queryRunner.query(`ALTER TABLE "opportunity_trackings" DROP CONSTRAINT "FK_f7377ab7b0daab81737dab9d74b"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_6cb1c429c65cfa6c137262f524d"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_0caa550ba1e8af228a444f41c50"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_dd8f6e7c9c029545b56717efe07"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_6b809748751441914b5a7068cc5"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_51392868612157f01fc61a6ee2d"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_be657f80d27287715b533b080fa"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP CONSTRAINT "FK_b12ed2b583eebb41169a8fb64de"`);
        await queryRunner.query(`ALTER TABLE "opportunity_products" DROP CONSTRAINT "FK_71f53a0a0d3d828a4b24e81a64e"`);
        await queryRunner.query(`ALTER TABLE "opportunity_products" DROP CONSTRAINT "FK_d64e2b99803fd0de5f48b40202d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_de1043dff8f68e83a20480b00f7"`);
        await queryRunner.query(`ALTER TABLE "product_files" DROP CONSTRAINT "FK_56627602b737452ac8e95a0ac78"`);
        await queryRunner.query(`ALTER TABLE "opportunity_files" DROP CONSTRAINT "FK_4dab24c743f43a61cdcb9c52658"`);
        await queryRunner.query(`ALTER TABLE "tblstagescatalog" DROP CONSTRAINT "FK_5722459e77f4db2a760c7b888db"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_5016a1ccedbea5f26d46376d6b2"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "FK_d006d797a7fb8586365e3a741ec"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "activity"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "activity" character varying(80) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('admin', 'executive')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'executive'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "opportunity_trackings" ALTER COLUMN "stage_id" TYPE "public"."opportunity_trackings_stage_id_enum" USING "stage_id"::text::"public"."opportunity_trackings_stage_id_enum"`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "empresa" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "cliente_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD CONSTRAINT "FK_b12ed2b583eebb41169a8fb64de" FOREIGN KEY ("cliente_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "empresa" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "correo" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "activity_id"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP COLUMN "notified"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "typeActivityId"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "priority"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "stage_entered_at"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "licenciamiento_id"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "tipo_entrega_id"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "linea_negocio_id"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "stage_id"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "pipeline_id"`);
        await queryRunner.query(`ALTER TABLE "opportunities" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "companyId"`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD "opportunity_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."activities_activitytype_enum" AS ENUM('Correo', 'Presentación Servicios Presencial', 'Presentación Servicios En Línea', 'Evento', 'Seguimiento Oportunidad Línea', 'Llamada', 'Seguimiento Oportunidad Presencial', 'Otros')`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "activityType" "public"."activities_activitytype_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."opportunities_licenciamiento_enum" AS ENUM('No Aplica', 'Microsoft', 'IBM', 'Qlik', 'Alteryx', 'KNIME')`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "licenciamiento" "public"."opportunities_licenciamiento_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."opportunities_tipo_entrega_enum" AS ENUM('Proyecto', 'Licencia', 'Asignacion', 'Bolsa de Horas')`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "tipo_entrega" "public"."opportunities_tipo_entrega_enum" NOT NULL DEFAULT 'Proyecto'`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "tipo_entrega" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."opportunities_linea_negocio_enum" AS ENUM('Datos', 'Desarrollo', 'RH')`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "linea_negocio" "public"."opportunities_linea_negocio_enum" NOT NULL DEFAULT 'Datos'`);
        await queryRunner.query(`ALTER TABLE "opportunities" ALTER COLUMN "linea_negocio" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."opportunities_etapa_enum" AS ENUM('Nuevo', 'Descubrimiento', 'Estimación', 'Propuesta', 'Negociación', 'Ganada', 'Perdida', 'Cancelada', 'Standby')`);
        await queryRunner.query(`ALTER TABLE "opportunities" ADD "etapa" "public"."opportunities_etapa_enum" NOT NULL DEFAULT 'Nuevo'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0461d2145d72ac02cb1f4496a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc2f54f67216c56a0e28d7040f"`);
        await queryRunner.query(`DROP TABLE "activity_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73fb9c255cb264c56fc9783295"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7d00109580422761c6da2aa35"`);
        await queryRunner.query(`DROP TABLE "opportunity_contacts"`);
        await queryRunner.query(`DROP TABLE "ai_agent_configs"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "ai_sub_agents"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TABLE "channel_configs"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "tbloportunitylabels"`);
        await queryRunner.query(`DROP TABLE "tbltypeactivities"`);
        await queryRunner.query(`DROP TABLE "dashboard_indicators"`);
        await queryRunner.query(`DROP TABLE "transaction_history"`);
        await queryRunner.query(`DROP TABLE "ticket_interactions"`);
        await queryRunner.query(`DROP TABLE "helpdesk_cron_config"`);
        await queryRunner.query(`DROP TABLE "tenant_renewal_queue"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TABLE "helpdesks"`);
        await queryRunner.query(`DROP TABLE "ticket_stages"`);
        await queryRunner.query(`DROP TABLE "tblicensings"`);
        await queryRunner.query(`DROP TABLE "tbldeliverytypes"`);
        await queryRunner.query(`DROP TABLE "tblbusinesslines"`);
        await queryRunner.query(`DROP TABLE "opportunity_products"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product_files"`);
        await queryRunner.query(`DROP TABLE "opportunity_files"`);
        await queryRunner.query(`DROP TABLE "tblpipelinescatalog"`);
        await queryRunner.query(`DROP TABLE "tblstagescatalog"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`ALTER TYPE "public"."opportunity_trackings_stage_id_enum" RENAME TO "opportunity_trackings_stage_enum"`);
        await queryRunner.query(`ALTER TABLE "opportunity_trackings" RENAME COLUMN "stage_id" TO "stage"`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_3ce7e1ecb0bee6873c2a6566ed6" FOREIGN KEY ("opportunity_id") REFERENCES "opportunities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
